# Generated by Django 5.2.1 on 2026-04-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
