# Generated by Django 5.2.6 on 2026-01-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_default_color', models.CharField(default='#F7F0DB', max_length=7)),
                ('text_default_color', models.CharField(default='#1E180D', max_length=7)),
                ('action_primary_default_color', models.CharField(default='#BF4630', max_length=7)),
                ('action_secondary_default_color', models.CharField(default='#5A83A6', max_length=7)),
            ],
            options={
                'verbose_name': 'Theme settings',
            },
        ),
    ]
