# Generated by Django 5.2.6 on 2026-01-03 07:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_themesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='action_primary_default_color',
            field=colorfield.fields.ColorField(default='#BF4630', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='action_secondary_default_color',
            field=colorfield.fields.ColorField(default='#5A83A6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='background_default_color',
            field=colorfield.fields.ColorField(default='#F7F0DB', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='text_default_color',
            field=colorfield.fields.ColorField(default='#1E180D', image_field=None, max_length=25, samples=None),
        ),
    ]
