# Generated by Django 5.2.1 on 2026-04-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
    ]
