# Generated by Django 5.2.6 on 2025-12-20 07:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#777777', image_field=None, max_length=25, samples=None),
        ),
    ]
