# Generated by Django 5.2.1 on 2026-03-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
