# Generated by Django 5.2.1 on 2026-03-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_options_brand_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
