# Generated by Django 5.2.1 on 2026-04-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_variant'),
        ('products', '0008_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
